import type { Config } from 'tailwindcss';
import typography from '@tailwindcss/typography';

export const chatuiTailwindPreset: Omit<Config, 'content'> = {
  theme: {
    extend: {
      colors: {
        white: 'var(--chatui-color-static-white)',
        black: 'var(--chatui-color-static-black)',
        bgLight: 'var(--chatui-color-canvas)',
        surface: 'var(--chatui-color-surface)',
        surfaceMuted: 'var(--chatui-color-surface-muted)',
        primaryText: 'var(--chatui-color-text-primary)',
        secondaryText: 'var(--chatui-color-text-secondary)',
        tertiaryText: 'var(--chatui-color-text-tertiary)',
        mutedText: 'var(--chatui-color-text-muted)',
        headerText: 'var(--chatui-color-text-header)',
        strongText: 'var(--chatui-color-text-strong)',
        emphasisText: 'var(--chatui-color-text-emphasis)',
        borderGray: 'var(--chatui-color-border)',
        borderSoft: 'var(--chatui-color-border-soft)',
        controlBorderDefault: 'var(--chatui-color-control-border-default)',
        controlBorderHover: 'var(--chatui-color-control-border-hover)',
        controlBorder: 'var(--chatui-color-control-border)',
        lineSubtle: 'var(--chatui-color-line-subtle)',
        lineSoft: 'var(--chatui-color-line-soft)',
        projectTagSurface: 'var(--chatui-color-project-tag-surface)',
        projectConversationHover: 'var(--chatui-color-project-conversation-hover)',
        aiUsageCard: 'var(--chatui-color-ai-usage-card)',
        aiUsageTooltip: 'var(--chatui-color-ai-usage-tooltip)',
        aiUsageBar: 'var(--chatui-color-ai-usage-bar)',
        aiUsageBarHover: 'var(--chatui-color-ai-usage-bar-hover)',
        toolCodeSurface: 'var(--chatui-color-tool-code-surface)',
        skillCreate: 'var(--chatui-color-skill-create)',
        skillCreateHover: 'var(--chatui-color-skill-create-hover)',
        skillRiskLow: 'var(--chatui-color-skill-risk-low)',
        skillRiskMedium: 'var(--chatui-color-skill-risk-medium)',
        skillCheckbox: 'var(--chatui-color-skill-checkbox)',
        skillSelectedBorder: 'var(--chatui-color-skill-selected-border)',
        skillSelectedSurface: 'var(--chatui-color-skill-selected-surface)',
        skillTagSurface: 'var(--chatui-color-skill-tag-surface)',
        skillCancelHover: 'var(--chatui-color-skill-cancel-hover)',
        skillActionDisabled: 'var(--chatui-color-skill-action-disabled)',
        chatSkillBorder: 'var(--chatui-color-chat-skill-border)',
        chatSkillSurface: 'var(--chatui-color-chat-skill-surface)',
        chatSkillText: 'var(--chatui-color-chat-skill-text)',
        chatSkillTextMuted: 'var(--chatui-color-chat-skill-text-muted)',
        chatSkillHover: 'var(--chatui-color-chat-skill-hover)',
        chatReferenceBorder: 'var(--chatui-color-chat-reference-border)',
        chatReferenceSurface: 'var(--chatui-color-chat-reference-surface)',
        chatReferenceText: 'var(--chatui-color-chat-reference-text)',
        chatReferenceTextMuted: 'var(--chatui-color-chat-reference-text-muted)',
        chatReferenceTextHover: 'var(--chatui-color-chat-reference-text-hover)',
        chatReferenceHover: 'var(--chatui-color-chat-reference-hover)',
        chatAttachmentBorder: 'var(--chatui-color-chat-attachment-border)',
        chatAttachmentIconSurface: 'var(--chatui-color-chat-attachment-icon-surface)',
        chatAttachmentTextMuted: 'var(--chatui-color-chat-attachment-text-muted)',
        chatAttachmentHover: 'var(--chatui-color-chat-attachment-hover)',
        chatFloatingSurface: 'var(--chatui-color-chat-floating-surface)',
        chatPopupBorder: 'var(--chatui-color-chat-popup-border)',
        chatMenuActive: 'var(--chatui-color-chat-menu-active)',
        chatMenuHover: 'var(--chatui-color-chat-menu-hover)',
        chatMenuIcon: 'var(--chatui-color-chat-menu-icon)',
        chatWebStep: 'var(--chatui-color-chat-web-step)',
        chatToolStep: 'var(--chatui-color-chat-tool-step)',
        chatContentDivider: 'var(--chatui-color-chat-content-divider)',
        chatContentMuted: 'var(--chatui-color-chat-content-muted)',
        chatWorkspaceDivider: 'var(--chatui-color-chat-workspace-divider)',
        chatWorkspaceActionSurface: 'var(--chatui-color-chat-workspace-action-surface)',
        chatTimelineBorder: 'var(--chatui-color-chat-timeline-border)',
        chatTimelineText: 'var(--chatui-color-chat-timeline-text)',
        chatTimelineTextHover: 'var(--chatui-color-chat-timeline-text-hover)',
        chatTimelineMarker: 'var(--chatui-color-chat-timeline-marker)',
        chatTimelineScrollbar: 'var(--chatui-color-chat-timeline-scrollbar)',
        chatShareDockSurface: 'var(--chatui-color-chat-share-dock-surface)',
        chatShareLinkBorder: 'var(--chatui-color-chat-share-link-border)',
        chatShareLinkSurface: 'var(--chatui-color-chat-share-link-surface)',
        chatPanelItemSurface: 'var(--chatui-color-chat-panel-item-surface)',
        chatPreviewContentSurface: 'var(--chatui-color-chat-preview-content-surface)',
        shellNavActive: 'var(--chatui-color-shell-nav-active)',
        shellChatEditBorder: 'var(--chatui-color-shell-chat-edit-border)',
        shellFrameBorder: 'var(--chatui-color-shell-frame-border)',
        shellDivider: 'var(--chatui-color-shell-divider)',
        shellTextFaint: 'var(--chatui-color-shell-text-faint)',
        shellChatBadgeSurface: 'var(--chatui-color-shell-chat-badge-surface)',
        shellChatBadgeText: 'var(--chatui-color-shell-chat-badge-text)',
        shellAvatarSurface: 'var(--chatui-color-shell-avatar-surface)',
        shellHistoryHover: 'var(--chatui-color-shell-history-hover)',
        shellTaskBadgeSurface: 'var(--chatui-color-shell-task-badge-surface)',
        shellTaskBadgeText: 'var(--chatui-color-shell-task-badge-text)',
        homeHeaderSurface: 'var(--chatui-color-home-header-surface)',
        authCardBorder: 'var(--chatui-color-auth-card-border)',
        authCardSurface: 'var(--chatui-color-auth-card-surface)',
        authTextMuted: 'var(--chatui-color-auth-text-muted)',
        authTextDefault: 'var(--chatui-color-auth-text-default)',
        authTextStrong: 'var(--chatui-color-auth-text-strong)',
        authTextFaint: 'var(--chatui-color-auth-text-faint)',
        authLink: 'var(--chatui-color-auth-link)',
        authDivider: 'var(--chatui-color-auth-divider)',
        authFieldError: 'var(--chatui-color-auth-field-error)',
        authFieldErrorFocus: 'var(--chatui-color-auth-field-error-focus)',
        authErrorText: 'var(--chatui-color-auth-error-text)',
        authSuccessPulse: 'var(--chatui-color-auth-success-pulse)',
        authToastSurface: 'var(--chatui-color-auth-toast-surface)',
        authToastBorder: 'var(--chatui-color-auth-toast-border)',
        authToastText: 'var(--chatui-color-auth-toast-text)',
        primary: 'var(--chatui-color-brand-primary)',
        'primary-hover': 'var(--chatui-color-brand-primary-hover)',
        'primary-soft': 'var(--chatui-color-brand-primary-soft)',
        'primary-soft-strong': 'var(--chatui-color-brand-primary-soft-strong)',
        success: 'var(--chatui-color-status-success)',
        'success-soft': 'var(--chatui-color-status-success-soft)',
        warning: 'var(--chatui-color-status-warning)',
        'warning-soft': 'var(--chatui-color-status-warning-soft)',
        danger: 'var(--chatui-color-status-danger)',
        'danger-hover': 'var(--chatui-color-status-danger-hover)',
        'danger-soft': 'var(--chatui-color-status-danger-soft)',
        brandFocus: 'var(--chatui-focus-ring-brand)',
        dangerFocus: 'var(--chatui-focus-ring-danger)',
        overlayMask: 'var(--chatui-overlay-mask)',
        overlaySurface: 'var(--chatui-overlay-surface-80)',
        scrollbar: 'var(--chatui-color-scrollbar-thumb)',
        'scrollbar-hover': 'var(--chatui-color-scrollbar-thumb-hover)',
        'scrollbar-subtle': 'var(--chatui-color-scrollbar-subtle)',
        'scrollbar-subtle-hover': 'var(--chatui-color-scrollbar-subtle-hover)',
      },
      fontSize: {
        xs: ['12px', '16px'],
        sm: ['14px', '20px'],
        base: ['16px', '24px'],
        lg: ['18px', '26px'],
        xl: ['20px', '28px'],
        '2xl': ['24px', '32px'],
        '3xl': ['28px', '36px'],
        '4xl': ['32px', '40px'],
        '5xl': ['36px', '44px'],
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '24px',
        '3xl': '32px',
        full: '999px',
      },
      boxShadow: {
        sm: 'var(--chatui-shadow-sm)',
        md: 'var(--chatui-shadow-md)',
        lg: 'var(--chatui-shadow-lg)',
        chatPopup: 'var(--chatui-shadow-chat-popup)',
        chatTooltip: 'var(--chatui-shadow-chat-tooltip)',
        chatHint: 'var(--chatui-shadow-chat-hint)',
        chatTimeline: 'var(--chatui-shadow-chat-timeline)',
        authCard: 'var(--chatui-shadow-auth-card)',
        shellWarning: 'var(--chatui-shadow-shell-warning)',
      },
      backgroundImage: {
        authBackdropCenter: 'var(--chatui-auth-backdrop-center)',
        authBackdropCorner: 'var(--chatui-auth-backdrop-corner)',
        authTitle: 'var(--chatui-auth-title-gradient)',
        skillCardHover: 'var(--chatui-skill-card-hover)',
      },
    },
  },
  plugins: [typography],
};

export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './showcase/**/*.{js,ts,jsx,tsx}'],
  presets: [chatuiTailwindPreset],
} satisfies Config;
